BEGIN;

-- Xóa Cục nhà trường
DELETE FROM provinces WHERE id = '00';
DELETE FROM high_schools WHERE province_code = '00';

-- Xóa toàn bộ trường cấp 3 cũ để nạp lại đầy đủ có dấu
DELETE FROM high_schools;

-- Nạp 63 Tỉnh/Thành
INSERT INTO provinces (id, name) VALUES ('01', 'Thành phố Hà Nội') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('02', 'Thành phố Hồ Chí Minh') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('03', 'Thành phố Hải Phòng') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('04', 'Thành phố Đà Nẵng') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('05', 'Tỉnh Hà Giang') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('06', 'Tỉnh Cao Bằng') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('07', 'Tỉnh Lai Châu') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('08', 'Tỉnh Lào Cai') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('09', 'Tỉnh Tuyên Quang') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('10', 'Tỉnh Lạng Sơn') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('11', 'Tỉnh Bắc Kạn') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('12', 'Tỉnh Thái Nguyên') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('13', 'Tỉnh Yên Bái') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('14', 'Tỉnh Sơn La') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('15', 'Tỉnh Phú Thọ') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('16', 'Tỉnh Vĩnh Phúc') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('17', 'Tỉnh Quảng Ninh') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('18', 'Tỉnh Bắc Giang') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('19', 'Tỉnh Bắc Ninh') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('21', 'Tỉnh Hải Dương') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('22', 'Tỉnh Hưng Yên') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('23', 'Tỉnh Hoà Bình') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('24', 'Tỉnh Hà Nam') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('25', 'Tỉnh Nam Định') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('26', 'Tỉnh Thái Bình') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('27', 'Tỉnh Ninh Bình') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('28', 'Tỉnh Thanh Hoá') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('29', 'Tỉnh Nghệ An') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('30', 'Tỉnh Hà Tĩnh') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('31', 'Tỉnh Quảng Bình') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('32', 'Tỉnh Quảng Trị') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('33', 'Tỉnh Thừa Thiên Huế') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('34', 'Tỉnh Quảng Nam') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('35', 'Tỉnh Quảng Ngãi') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('36', 'Tỉnh Kon Tum') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('37', 'Tỉnh Bình Định') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('38', 'Tỉnh Gia Lai') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('39', 'Tỉnh Phú Yên') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('40', 'Tỉnh Đắk Lắk') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('41', 'Tỉnh Khánh Hoà') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('42', 'Tỉnh Lâm Đồng') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('43', 'Tỉnh Bình Phước') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('44', 'Tỉnh Bình Dương') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('45', 'Tỉnh Ninh Thuận') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('46', 'Tỉnh Tây Ninh') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('47', 'Tỉnh Bình Thuận') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('48', 'Tỉnh Đồng Nai') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('49', 'Tỉnh Long An') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('50', 'Tỉnh Đồng Tháp') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('51', 'Tỉnh An Giang') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('52', 'Tỉnh Bà Rịa - Vũng Tàu') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('53', 'Tỉnh Tiền Giang') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('54', 'Tỉnh Kiên Giang') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('55', 'Thành phố Cần Thơ') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('56', 'Tỉnh Bến Tre') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('57', 'Tỉnh Vĩnh Long') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('58', 'Tỉnh Trà Vinh') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('59', 'Tỉnh Sóc Trăng') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('60', 'Tỉnh Bạc Liêu') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('61', 'Tỉnh Cà Mau') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('62', 'Tỉnh Điện Biên') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('63', 'Tỉnh Đắk Nông') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO provinces (id, name) VALUES ('64', 'Tỉnh Hậu Giang') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;

-- Nạp danh sách Trường THPT cho 63 Tỉnh/Thành
INSERT INTO high_schools (id, name, province_code, code) VALUES ('01TH001', 'THPT Chu Văn An', '01', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('01TH002', 'THPT Kim Liên', '01', 'KL');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('01TH003', 'THPT Việt Đức', '01', 'V');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('01TH004', 'THPT Trần Hưng Đạo', '01', 'TH');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('01TH005', 'THPT Hà Nội - Amsterdam', '01', 'HNA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('01TH006', 'THPT Phan Đình Phùng', '01', 'PP');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('02TH001', 'THPT Lê Hồng Phong', '02', 'LHP');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('02TH002', 'THPT Nguyễn Thượng Hiền', '02', 'NTH');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('02TH003', 'THPT Trần Khai Nguyên', '02', 'TKN');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('02TH004', 'THPT Nguyễn Thị Minh Khai', '02', 'NTMK');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('02TH005', 'THPT Gia Định', '02', 'G');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('02TH006', 'THPT Bùi Thị Xuân', '02', 'BTX');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('03TH001', 'THPT Chuyên Trần Phú', '03', 'CTP');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('03TH002', 'THPT Ngô Quyền', '03', 'NQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('03TH003', 'THPT Thái Phiên', '03', 'TP');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('03TH004', 'THPT Lê Quý Đôn', '03', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('04TH001', 'THPT Phan Châu Trinh', '04', 'PCT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('04TH002', 'THPT Trần Phú', '04', 'TP');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('04TH003', 'THPT Hoàng Hoa Thám', '04', 'HHT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('04TH004', 'THPT Chuyên Lê Quý Đôn', '04', 'CLQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('04TH005', 'THPT Nguyễn Trãi', '04', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('04TH006', 'THPT Thái Phiên', '04', 'TP');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('05TH001', 'THPT Chuyên Hà Giang', '05', 'CHG');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('05TH002', 'THPT Số 1 Hà Giang', '05', 'SHG');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('05TH003', 'THPT Số 2 Hà Giang', '05', 'SHG');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('05TH004', 'THPT Nguyễn Trãi', '05', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('05TH005', 'THPT Lê Quý Đôn', '05', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('05TH006', 'THPT Chu Văn An', '05', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('06TH001', 'THPT Chuyên Cao Bằng', '06', 'CCB');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('06TH002', 'THPT Số 1 Cao Bằng', '06', 'SCB');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('06TH003', 'THPT Số 2 Cao Bằng', '06', 'SCB');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('06TH004', 'THPT Nguyễn Trãi', '06', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('06TH005', 'THPT Lê Quý Đôn', '06', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('06TH006', 'THPT Chu Văn An', '06', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('07TH001', 'THPT Chuyên Lai Châu', '07', 'CLC');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('07TH002', 'THPT Số 1 Lai Châu', '07', 'SLC');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('07TH003', 'THPT Số 2 Lai Châu', '07', 'SLC');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('07TH004', 'THPT Nguyễn Trãi', '07', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('07TH005', 'THPT Lê Quý Đôn', '07', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('07TH006', 'THPT Chu Văn An', '07', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('08TH001', 'THPT Chuyên Lào Cai', '08', 'CLC');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('08TH002', 'THPT Số 1 Lào Cai', '08', 'SLC');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('08TH003', 'THPT Số 2 Lào Cai', '08', 'SLC');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('08TH004', 'THPT Nguyễn Trãi', '08', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('08TH005', 'THPT Lê Quý Đôn', '08', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('08TH006', 'THPT Chu Văn An', '08', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('09TH001', 'THPT Chuyên Tuyên Quang', '09', 'CTQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('09TH002', 'THPT Số 1 Tuyên Quang', '09', 'STQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('09TH003', 'THPT Số 2 Tuyên Quang', '09', 'STQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('09TH004', 'THPT Nguyễn Trãi', '09', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('09TH005', 'THPT Lê Quý Đôn', '09', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('09TH006', 'THPT Chu Văn An', '09', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('10TH001', 'THPT Chuyên Lạng Sơn', '10', 'CLS');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('10TH002', 'THPT Số 1 Lạng Sơn', '10', 'SLS');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('10TH003', 'THPT Số 2 Lạng Sơn', '10', 'SLS');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('10TH004', 'THPT Nguyễn Trãi', '10', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('10TH005', 'THPT Lê Quý Đôn', '10', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('10TH006', 'THPT Chu Văn An', '10', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('11TH001', 'THPT Chuyên Bắc Kạn', '11', 'CBK');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('11TH002', 'THPT Số 1 Bắc Kạn', '11', 'SBK');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('11TH003', 'THPT Số 2 Bắc Kạn', '11', 'SBK');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('11TH004', 'THPT Nguyễn Trãi', '11', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('11TH005', 'THPT Lê Quý Đôn', '11', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('11TH006', 'THPT Chu Văn An', '11', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('12TH001', 'THPT Chuyên Thái Nguyên', '12', 'CTN');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('12TH002', 'THPT Số 1 Thái Nguyên', '12', 'STN');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('12TH003', 'THPT Số 2 Thái Nguyên', '12', 'STN');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('12TH004', 'THPT Nguyễn Trãi', '12', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('12TH005', 'THPT Lê Quý Đôn', '12', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('12TH006', 'THPT Chu Văn An', '12', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('13TH001', 'THPT Chuyên Yên Bái', '13', 'CYB');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('13TH002', 'THPT Số 1 Yên Bái', '13', 'SYB');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('13TH003', 'THPT Số 2 Yên Bái', '13', 'SYB');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('13TH004', 'THPT Nguyễn Trãi', '13', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('13TH005', 'THPT Lê Quý Đôn', '13', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('13TH006', 'THPT Chu Văn An', '13', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('14TH001', 'THPT Chuyên Sơn La', '14', 'CSL');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('14TH002', 'THPT Số 1 Sơn La', '14', 'SSL');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('14TH003', 'THPT Số 2 Sơn La', '14', 'SSL');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('14TH004', 'THPT Nguyễn Trãi', '14', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('14TH005', 'THPT Lê Quý Đôn', '14', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('14TH006', 'THPT Chu Văn An', '14', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('15TH001', 'THPT Chuyên Phú Thọ', '15', 'CPT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('15TH002', 'THPT Số 1 Phú Thọ', '15', 'SPT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('15TH003', 'THPT Số 2 Phú Thọ', '15', 'SPT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('15TH004', 'THPT Nguyễn Trãi', '15', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('15TH005', 'THPT Lê Quý Đôn', '15', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('15TH006', 'THPT Chu Văn An', '15', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('16TH001', 'THPT Chuyên Vĩnh Phúc', '16', 'CVP');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('16TH002', 'THPT Số 1 Vĩnh Phúc', '16', 'SVP');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('16TH003', 'THPT Số 2 Vĩnh Phúc', '16', 'SVP');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('16TH004', 'THPT Nguyễn Trãi', '16', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('16TH005', 'THPT Lê Quý Đôn', '16', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('16TH006', 'THPT Chu Văn An', '16', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('17TH001', 'THPT Chuyên Quảng Ninh', '17', 'CQN');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('17TH002', 'THPT Số 1 Quảng Ninh', '17', 'SQN');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('17TH003', 'THPT Số 2 Quảng Ninh', '17', 'SQN');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('17TH004', 'THPT Nguyễn Trãi', '17', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('17TH005', 'THPT Lê Quý Đôn', '17', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('17TH006', 'THPT Chu Văn An', '17', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('18TH001', 'THPT Chuyên Bắc Giang', '18', 'CBG');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('18TH002', 'THPT Số 1 Bắc Giang', '18', 'SBG');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('18TH003', 'THPT Số 2 Bắc Giang', '18', 'SBG');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('18TH004', 'THPT Nguyễn Trãi', '18', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('18TH005', 'THPT Lê Quý Đôn', '18', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('18TH006', 'THPT Chu Văn An', '18', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('19TH001', 'THPT Chuyên Bắc Ninh', '19', 'CBN');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('19TH002', 'THPT Số 1 Bắc Ninh', '19', 'SBN');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('19TH003', 'THPT Số 2 Bắc Ninh', '19', 'SBN');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('19TH004', 'THPT Nguyễn Trãi', '19', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('19TH005', 'THPT Lê Quý Đôn', '19', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('19TH006', 'THPT Chu Văn An', '19', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('21TH001', 'THPT Chuyên Hải Dương', '21', 'CHD');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('21TH002', 'THPT Số 1 Hải Dương', '21', 'SHD');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('21TH003', 'THPT Số 2 Hải Dương', '21', 'SHD');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('21TH004', 'THPT Nguyễn Trãi', '21', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('21TH005', 'THPT Lê Quý Đôn', '21', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('21TH006', 'THPT Chu Văn An', '21', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('22TH001', 'THPT Chuyên Hưng Yên', '22', 'CHY');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('22TH002', 'THPT Số 1 Hưng Yên', '22', 'SHY');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('22TH003', 'THPT Số 2 Hưng Yên', '22', 'SHY');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('22TH004', 'THPT Nguyễn Trãi', '22', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('22TH005', 'THPT Lê Quý Đôn', '22', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('22TH006', 'THPT Chu Văn An', '22', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('23TH001', 'THPT Chuyên Hoà Bình', '23', 'CHB');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('23TH002', 'THPT Số 1 Hoà Bình', '23', 'SHB');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('23TH003', 'THPT Số 2 Hoà Bình', '23', 'SHB');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('23TH004', 'THPT Nguyễn Trãi', '23', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('23TH005', 'THPT Lê Quý Đôn', '23', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('23TH006', 'THPT Chu Văn An', '23', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('24TH001', 'THPT Chuyên Hà Nam', '24', 'CHN');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('24TH002', 'THPT Số 1 Hà Nam', '24', 'SHN');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('24TH003', 'THPT Số 2 Hà Nam', '24', 'SHN');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('24TH004', 'THPT Nguyễn Trãi', '24', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('24TH005', 'THPT Lê Quý Đôn', '24', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('24TH006', 'THPT Chu Văn An', '24', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('25TH001', 'THPT Chuyên Nam Định', '25', 'CN');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('25TH002', 'THPT Số 1 Nam Định', '25', 'SN');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('25TH003', 'THPT Số 2 Nam Định', '25', 'SN');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('25TH004', 'THPT Nguyễn Trãi', '25', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('25TH005', 'THPT Lê Quý Đôn', '25', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('25TH006', 'THPT Chu Văn An', '25', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('26TH001', 'THPT Chuyên Thái Bình', '26', 'CTB');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('26TH002', 'THPT Số 1 Thái Bình', '26', 'STB');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('26TH003', 'THPT Số 2 Thái Bình', '26', 'STB');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('26TH004', 'THPT Nguyễn Trãi', '26', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('26TH005', 'THPT Lê Quý Đôn', '26', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('26TH006', 'THPT Chu Văn An', '26', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('27TH001', 'THPT Chuyên Ninh Bình', '27', 'CNB');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('27TH002', 'THPT Số 1 Ninh Bình', '27', 'SNB');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('27TH003', 'THPT Số 2 Ninh Bình', '27', 'SNB');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('27TH004', 'THPT Nguyễn Trãi', '27', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('27TH005', 'THPT Lê Quý Đôn', '27', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('27TH006', 'THPT Chu Văn An', '27', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('28TH001', 'THPT Chuyên Thanh Hoá', '28', 'CTH');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('28TH002', 'THPT Số 1 Thanh Hoá', '28', 'STH');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('28TH003', 'THPT Số 2 Thanh Hoá', '28', 'STH');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('28TH004', 'THPT Nguyễn Trãi', '28', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('28TH005', 'THPT Lê Quý Đôn', '28', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('28TH006', 'THPT Chu Văn An', '28', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('29TH001', 'THPT Chuyên Nghệ An', '29', 'CNA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('29TH002', 'THPT Số 1 Nghệ An', '29', 'SNA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('29TH003', 'THPT Số 2 Nghệ An', '29', 'SNA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('29TH004', 'THPT Nguyễn Trãi', '29', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('29TH005', 'THPT Lê Quý Đôn', '29', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('29TH006', 'THPT Chu Văn An', '29', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('30TH001', 'THPT Chuyên Hà Tĩnh', '30', 'CHT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('30TH002', 'THPT Số 1 Hà Tĩnh', '30', 'SHT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('30TH003', 'THPT Số 2 Hà Tĩnh', '30', 'SHT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('30TH004', 'THPT Nguyễn Trãi', '30', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('30TH005', 'THPT Lê Quý Đôn', '30', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('30TH006', 'THPT Chu Văn An', '30', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('31TH001', 'THPT Chuyên Quảng Bình', '31', 'CQB');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('31TH002', 'THPT Số 1 Quảng Bình', '31', 'SQB');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('31TH003', 'THPT Số 2 Quảng Bình', '31', 'SQB');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('31TH004', 'THPT Nguyễn Trãi', '31', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('31TH005', 'THPT Lê Quý Đôn', '31', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('31TH006', 'THPT Chu Văn An', '31', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('32TH001', 'THPT Chuyên Quảng Trị', '32', 'CQT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('32TH002', 'THPT Số 1 Quảng Trị', '32', 'SQT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('32TH003', 'THPT Số 2 Quảng Trị', '32', 'SQT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('32TH004', 'THPT Nguyễn Trãi', '32', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('32TH005', 'THPT Lê Quý Đôn', '32', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('32TH006', 'THPT Chu Văn An', '32', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('33TH001', 'THPT Chuyên Thừa Thiên Huế', '33', 'CTTH');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('33TH002', 'THPT Số 1 Thừa Thiên Huế', '33', 'STTH');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('33TH003', 'THPT Số 2 Thừa Thiên Huế', '33', 'STTH');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('33TH004', 'THPT Nguyễn Trãi', '33', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('33TH005', 'THPT Lê Quý Đôn', '33', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('33TH006', 'THPT Chu Văn An', '33', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('34TH001', 'THPT Chuyên Quảng Nam', '34', 'CQN');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('34TH002', 'THPT Số 1 Quảng Nam', '34', 'SQN');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('34TH003', 'THPT Số 2 Quảng Nam', '34', 'SQN');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('34TH004', 'THPT Nguyễn Trãi', '34', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('34TH005', 'THPT Lê Quý Đôn', '34', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('34TH006', 'THPT Chu Văn An', '34', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('35TH001', 'THPT Chuyên Quảng Ngãi', '35', 'CQN');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('35TH002', 'THPT Số 1 Quảng Ngãi', '35', 'SQN');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('35TH003', 'THPT Số 2 Quảng Ngãi', '35', 'SQN');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('35TH004', 'THPT Nguyễn Trãi', '35', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('35TH005', 'THPT Lê Quý Đôn', '35', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('35TH006', 'THPT Chu Văn An', '35', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('36TH001', 'THPT Chuyên Kon Tum', '36', 'CKT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('36TH002', 'THPT Số 1 Kon Tum', '36', 'SKT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('36TH003', 'THPT Số 2 Kon Tum', '36', 'SKT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('36TH004', 'THPT Nguyễn Trãi', '36', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('36TH005', 'THPT Lê Quý Đôn', '36', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('36TH006', 'THPT Chu Văn An', '36', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('37TH001', 'THPT Chuyên Bình Định', '37', 'CB');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('37TH002', 'THPT Số 1 Bình Định', '37', 'SB');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('37TH003', 'THPT Số 2 Bình Định', '37', 'SB');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('37TH004', 'THPT Nguyễn Trãi', '37', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('37TH005', 'THPT Lê Quý Đôn', '37', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('37TH006', 'THPT Chu Văn An', '37', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('38TH001', 'THPT Chuyên Gia Lai', '38', 'CGL');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('38TH002', 'THPT Số 1 Gia Lai', '38', 'SGL');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('38TH003', 'THPT Số 2 Gia Lai', '38', 'SGL');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('38TH004', 'THPT Nguyễn Trãi', '38', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('38TH005', 'THPT Lê Quý Đôn', '38', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('38TH006', 'THPT Chu Văn An', '38', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('39TH001', 'THPT Chuyên Phú Yên', '39', 'CPY');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('39TH002', 'THPT Số 1 Phú Yên', '39', 'SPY');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('39TH003', 'THPT Số 2 Phú Yên', '39', 'SPY');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('39TH004', 'THPT Nguyễn Trãi', '39', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('39TH005', 'THPT Lê Quý Đôn', '39', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('39TH006', 'THPT Chu Văn An', '39', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('40TH001', 'THPT Chuyên Đắk Lắk', '40', 'CL');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('40TH002', 'THPT Số 1 Đắk Lắk', '40', 'SL');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('40TH003', 'THPT Số 2 Đắk Lắk', '40', 'SL');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('40TH004', 'THPT Nguyễn Trãi', '40', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('40TH005', 'THPT Lê Quý Đôn', '40', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('40TH006', 'THPT Chu Văn An', '40', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('41TH001', 'THPT Chuyên Khánh Hoà', '41', 'CKH');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('41TH002', 'THPT Số 1 Khánh Hoà', '41', 'SKH');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('41TH003', 'THPT Số 2 Khánh Hoà', '41', 'SKH');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('41TH004', 'THPT Nguyễn Trãi', '41', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('41TH005', 'THPT Lê Quý Đôn', '41', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('41TH006', 'THPT Chu Văn An', '41', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('42TH001', 'THPT Chuyên Lâm Đồng', '42', 'CL');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('42TH002', 'THPT Số 1 Lâm Đồng', '42', 'SL');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('42TH003', 'THPT Số 2 Lâm Đồng', '42', 'SL');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('42TH004', 'THPT Nguyễn Trãi', '42', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('42TH005', 'THPT Lê Quý Đôn', '42', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('42TH006', 'THPT Chu Văn An', '42', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('43TH001', 'THPT Chuyên Bình Phước', '43', 'CBP');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('43TH002', 'THPT Số 1 Bình Phước', '43', 'SBP');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('43TH003', 'THPT Số 2 Bình Phước', '43', 'SBP');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('43TH004', 'THPT Nguyễn Trãi', '43', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('43TH005', 'THPT Lê Quý Đôn', '43', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('43TH006', 'THPT Chu Văn An', '43', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('44TH001', 'THPT Chuyên Bình Dương', '44', 'CBD');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('44TH002', 'THPT Số 1 Bình Dương', '44', 'SBD');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('44TH003', 'THPT Số 2 Bình Dương', '44', 'SBD');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('44TH004', 'THPT Nguyễn Trãi', '44', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('44TH005', 'THPT Lê Quý Đôn', '44', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('44TH006', 'THPT Chu Văn An', '44', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('45TH001', 'THPT Chuyên Ninh Thuận', '45', 'CNT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('45TH002', 'THPT Số 1 Ninh Thuận', '45', 'SNT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('45TH003', 'THPT Số 2 Ninh Thuận', '45', 'SNT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('45TH004', 'THPT Nguyễn Trãi', '45', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('45TH005', 'THPT Lê Quý Đôn', '45', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('45TH006', 'THPT Chu Văn An', '45', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('46TH001', 'THPT Chuyên Tây Ninh', '46', 'CTN');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('46TH002', 'THPT Số 1 Tây Ninh', '46', 'STN');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('46TH003', 'THPT Số 2 Tây Ninh', '46', 'STN');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('46TH004', 'THPT Nguyễn Trãi', '46', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('46TH005', 'THPT Lê Quý Đôn', '46', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('46TH006', 'THPT Chu Văn An', '46', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('47TH001', 'THPT Chuyên Bình Thuận', '47', 'CBT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('47TH002', 'THPT Số 1 Bình Thuận', '47', 'SBT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('47TH003', 'THPT Số 2 Bình Thuận', '47', 'SBT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('47TH004', 'THPT Nguyễn Trãi', '47', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('47TH005', 'THPT Lê Quý Đôn', '47', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('47TH006', 'THPT Chu Văn An', '47', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('48TH001', 'THPT Chuyên Đồng Nai', '48', 'CN');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('48TH002', 'THPT Số 1 Đồng Nai', '48', 'SN');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('48TH003', 'THPT Số 2 Đồng Nai', '48', 'SN');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('48TH004', 'THPT Nguyễn Trãi', '48', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('48TH005', 'THPT Lê Quý Đôn', '48', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('48TH006', 'THPT Chu Văn An', '48', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('49TH001', 'THPT Chuyên Long An', '49', 'CLA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('49TH002', 'THPT Số 1 Long An', '49', 'SLA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('49TH003', 'THPT Số 2 Long An', '49', 'SLA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('49TH004', 'THPT Nguyễn Trãi', '49', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('49TH005', 'THPT Lê Quý Đôn', '49', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('49TH006', 'THPT Chu Văn An', '49', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('50TH001', 'THPT Chuyên Đồng Tháp', '50', 'CT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('50TH002', 'THPT Số 1 Đồng Tháp', '50', 'ST');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('50TH003', 'THPT Số 2 Đồng Tháp', '50', 'ST');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('50TH004', 'THPT Nguyễn Trãi', '50', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('50TH005', 'THPT Lê Quý Đôn', '50', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('50TH006', 'THPT Chu Văn An', '50', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('51TH001', 'THPT Chuyên An Giang', '51', 'CAG');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('51TH002', 'THPT Số 1 An Giang', '51', 'SAG');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('51TH003', 'THPT Số 2 An Giang', '51', 'SAG');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('51TH004', 'THPT Nguyễn Trãi', '51', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('51TH005', 'THPT Lê Quý Đôn', '51', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('51TH006', 'THPT Chu Văn An', '51', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('52TH001', 'THPT Chuyên Bà Rịa - Vũng Tàu', '52', 'CBRV');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('52TH002', 'THPT Số 1 Bà Rịa - Vũng Tàu', '52', 'SBRV');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('52TH003', 'THPT Số 2 Bà Rịa - Vũng Tàu', '52', 'SBRV');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('52TH004', 'THPT Nguyễn Trãi', '52', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('52TH005', 'THPT Lê Quý Đôn', '52', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('52TH006', 'THPT Chu Văn An', '52', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('53TH001', 'THPT Chuyên Tiền Giang', '53', 'CTG');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('53TH002', 'THPT Số 1 Tiền Giang', '53', 'STG');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('53TH003', 'THPT Số 2 Tiền Giang', '53', 'STG');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('53TH004', 'THPT Nguyễn Trãi', '53', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('53TH005', 'THPT Lê Quý Đôn', '53', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('53TH006', 'THPT Chu Văn An', '53', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('54TH001', 'THPT Chuyên Kiên Giang', '54', 'CKG');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('54TH002', 'THPT Số 1 Kiên Giang', '54', 'SKG');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('54TH003', 'THPT Số 2 Kiên Giang', '54', 'SKG');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('54TH004', 'THPT Nguyễn Trãi', '54', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('54TH005', 'THPT Lê Quý Đôn', '54', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('54TH006', 'THPT Chu Văn An', '54', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('55TH001', 'THPT Chuyên Cần Thơ', '55', 'CCT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('55TH002', 'THPT Số 1 Cần Thơ', '55', 'SCT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('55TH003', 'THPT Số 2 Cần Thơ', '55', 'SCT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('55TH004', 'THPT Nguyễn Trãi', '55', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('55TH005', 'THPT Lê Quý Đôn', '55', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('55TH006', 'THPT Chu Văn An', '55', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('56TH001', 'THPT Chuyên Bến Tre', '56', 'CBT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('56TH002', 'THPT Số 1 Bến Tre', '56', 'SBT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('56TH003', 'THPT Số 2 Bến Tre', '56', 'SBT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('56TH004', 'THPT Nguyễn Trãi', '56', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('56TH005', 'THPT Lê Quý Đôn', '56', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('56TH006', 'THPT Chu Văn An', '56', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('57TH001', 'THPT Chuyên Vĩnh Long', '57', 'CVL');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('57TH002', 'THPT Số 1 Vĩnh Long', '57', 'SVL');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('57TH003', 'THPT Số 2 Vĩnh Long', '57', 'SVL');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('57TH004', 'THPT Nguyễn Trãi', '57', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('57TH005', 'THPT Lê Quý Đôn', '57', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('57TH006', 'THPT Chu Văn An', '57', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('58TH001', 'THPT Chuyên Trà Vinh', '58', 'CTV');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('58TH002', 'THPT Số 1 Trà Vinh', '58', 'STV');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('58TH003', 'THPT Số 2 Trà Vinh', '58', 'STV');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('58TH004', 'THPT Nguyễn Trãi', '58', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('58TH005', 'THPT Lê Quý Đôn', '58', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('58TH006', 'THPT Chu Văn An', '58', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('59TH001', 'THPT Chuyên Sóc Trăng', '59', 'CST');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('59TH002', 'THPT Số 1 Sóc Trăng', '59', 'SST');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('59TH003', 'THPT Số 2 Sóc Trăng', '59', 'SST');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('59TH004', 'THPT Nguyễn Trãi', '59', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('59TH005', 'THPT Lê Quý Đôn', '59', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('59TH006', 'THPT Chu Văn An', '59', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('60TH001', 'THPT Chuyên Bạc Liêu', '60', 'CBL');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('60TH002', 'THPT Số 1 Bạc Liêu', '60', 'SBL');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('60TH003', 'THPT Số 2 Bạc Liêu', '60', 'SBL');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('60TH004', 'THPT Nguyễn Trãi', '60', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('60TH005', 'THPT Lê Quý Đôn', '60', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('60TH006', 'THPT Chu Văn An', '60', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('61TH001', 'THPT Chuyên Cà Mau', '61', 'CCM');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('61TH002', 'THPT Số 1 Cà Mau', '61', 'SCM');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('61TH003', 'THPT Số 2 Cà Mau', '61', 'SCM');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('61TH004', 'THPT Nguyễn Trãi', '61', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('61TH005', 'THPT Lê Quý Đôn', '61', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('61TH006', 'THPT Chu Văn An', '61', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('62TH001', 'THPT Chuyên Điện Biên', '62', 'CB');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('62TH002', 'THPT Số 1 Điện Biên', '62', 'SB');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('62TH003', 'THPT Số 2 Điện Biên', '62', 'SB');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('62TH004', 'THPT Nguyễn Trãi', '62', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('62TH005', 'THPT Lê Quý Đôn', '62', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('62TH006', 'THPT Chu Văn An', '62', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('63TH001', 'THPT Chuyên Đắk Nông', '63', 'CN');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('63TH002', 'THPT Số 1 Đắk Nông', '63', 'SN');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('63TH003', 'THPT Số 2 Đắk Nông', '63', 'SN');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('63TH004', 'THPT Nguyễn Trãi', '63', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('63TH005', 'THPT Lê Quý Đôn', '63', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('63TH006', 'THPT Chu Văn An', '63', 'CVA');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('64TH001', 'THPT Chuyên Hậu Giang', '64', 'CHG');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('64TH002', 'THPT Số 1 Hậu Giang', '64', 'SHG');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('64TH003', 'THPT Số 2 Hậu Giang', '64', 'SHG');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('64TH004', 'THPT Nguyễn Trãi', '64', 'NT');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('64TH005', 'THPT Lê Quý Đôn', '64', 'LQ');
INSERT INTO high_schools (id, name, province_code, code) VALUES ('64TH006', 'THPT Chu Văn An', '64', 'CVA');

COMMIT;
